apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: vparking

build:
  artifacts:
    - image: vparking-users
      context: src
      docker:
        dockerfile: ../Dockerfile
        
deploy:
  helm:
    releases:
      - name: vparking-settings
        chartPath: vparking-settings
        namespace: keycloak
        createNamespace: true
        valuesFiles:
          - vparking-settings/values.yaml
        version: 0.1.0
portForward:
  - resourceType: Service
    resourceName: vparking-settings
    namespace: keycloak
    port: 22
    localPort: 5022   