apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: vparking-order
build:
  artifacts:
    - image: vparking-orders
      context: src
      docker:
        dockerfile: Dockerfile-order
    - image: vparking-orders-update
      context: src
      docker:
        dockerfile: Dockerfile-update-order
  tagPolicy:
    sha256: {}
deploy:
  helm:
    releases:
      - name: vparking-orders
        chartPath: helm
        valuesFiles:
          - helm/values.yaml
        version: 0.1.0
      - name: postgresql
        chartPath: helm/charts/postgresql
        valuesFiles:
          - helm/charts/postgresql/values.yaml
        version: 16.3.5
      - name: common
        chartPath: helm/charts/postgresql/charts/common
        valuesFiles:
          - helm/charts/postgresql/charts/common/values.yaml
        version: 2.28.0
