controller:
  kind: DaemonSet
  reportNodeInternalIp: true
  enableLatencyMetrics: true
  metrics:
    enabled: true
  hostPort:
    enabled: true
    ports:
      http: 80
      https: 443
  service:
    type: NodePort
  config:
    entries:{ strict-validate-path-type: false}
prometheus:
  create: true
  scheme: "http"
  
  service:
    create: true

  serviceMonitor:
    create: true
    labels:
      { release: "monitoring" }
        

    endpoints:
      - path: "/metrics"
        port: prometheus
  