apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-{{.Values.serviceName}}
  {{- with .Values.podAnnotations}}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end}}
data:
  hello-world: "hello"
  db-username: "{{.Values.dbAuth.username}}"
  db-server: "{{.Values.dbAuth.server}}"
  {{- with (index .Values.ingress.hosts 0)}}
    {{- with (index .paths 0)}}
  swagger-prefix: "{{.pathPrefix}}"
    {{- end}}
  {{- end}}
  