apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: homework-5
build:
  artifacts:
    - image: vparking-settings-arm64
      context: src/VParking-Settings
      docker:
        dockerfile: Dockerfile
    - image: vparking-settings-arm64-update
      context: src/VParking-Settings
      docker:
        dockerfile: Dockerfile_update
deploy:
  helm:
    releases:
      
      - name: vparking
        chartPath: helm/vparking
        namespace: keycloak
        createNamespace: true
        skipBuildDependencies: true    
        valuesFiles:
          - helm/vparking/values.yaml
          - helm/postgres.yaml
        version: 0.1.0
     
