apiVersion: v1
kind: Secret
metadata:
  name: settings-secret
data:
  database-user-password: "{{.Values.postgresql.auth.password | b64enc}}"
  postgres-password: "{{.Values.postgresql.auth.postgresPassword | b64enc}}"