apiVersion: apps/v1
kind: Deployment
metadata:
    name: vparking-settings-deployment
spec:
    replicas: 3
    selector:
       matchLabels:
          app: vparking-settings-app
    template:
       metadata:
          labels:
             app: vparking-settings-app
       spec:
          containers:
          - name: settings
            image: reagafonov/vparking-settings-arm64:v20

            ports:
              - containerPort: 8080
            env:
              - name: "PG_CONNECTION_SERVER"
                valueFrom:
                  secretKeyRef:
                    name: settings-secret
                    key: database-server-name
              - name: "PG_CONNECTION_PASSWORD"
                valueFrom:
                  secretKeyRef:
                    key: database-user-password
                    name: settings-secret
              - name: "PG_CONNECTION_USER"
                valueFrom:
                  secretKeyRef:
                    key: database-user-name
                    name: settings-secret
           
          
