apiVersion: apps/v1
kind: Deployment
metadata:
    name: homework-deployment
spec:
    replicas: 3
    selector:
       matchLabels:
          app: homework-app
    template:
       metadata:
          labels:
             app: homework-app
       spec:
          containers:
          - name: homework-app-continer
            image: reagafonov/homework-py:v1
            ports:
              - name: web
                containerPort: 8000

