{{/*{{- if .Values.ingress.enabled -}}*/}}
{{/*apiVersion: networking.k8s.io/v1*/}}
{{/*kind: Ingress*/}}
{{/*metadata:*/}}
{{/*  name: monitoring-grafana*/}}
{{/*  labels:*/}}
{{/*    {{- include  "vparking-settings.labels" . | nindent 4 }}*/}}
{{/*  {{- with .Values.ingressGrafana.annotations }}*/}}
{{/*  annotations:*/}}
{{/*    {{- toYaml . | nindent 4 }}*/}}
{{/*  {{- end }}*/}}
{{/*spec:*/}}
{{/*  {{- with .Values.ingressGrafana.className }}*/}}
{{/*  ingressClassName: {{ . }}*/}}
{{/*  {{- end }}*/}}
{{/*  {{- if .Values.ingressGrafana.tls }}*/}}
{{/*  tls:*/}}
{{/*    {{- range .Values.ingressGrafana.tls }}*/}}
{{/*    - hosts:*/}}
{{/*        {{- range .hosts }}*/}}
{{/*        - {{ . | quote }}*/}}
{{/*        {{- end }}*/}}
{{/*      secretName: {{ .secretName }}*/}}
{{/*    {{- end }}*/}}
{{/*  {{- end }}*/}}
{{/*  rules:*/}}
{{/*    {{- range .Values.ingressGrafana.hosts }}*/}}
{{/*    - host: {{ .host | quote }}*/}}
{{/*      http:*/}}
{{/*        paths:*/}}
{{/*          {{- range .paths }}*/}}
{{/*          - path: {{ .pathPrefix }}{{.pathRegexSuffix}}*/}}
{{/*            {{- with .pathType }}*/}}
{{/*            pathType: {{ . }}*/}}
{{/*            {{- end }}*/}}
{{/*            backend:*/}}
{{/*              service:*/}}
{{/*                name: {{ include "vparking-settings.fullname" $ }}*/}}
{{/*                port:*/}}
{{/*                  number: {{ $.Values.service.port }}*/}}
{{/*          {{- end }}*/}}
{{/*    {{- end }}*/}}
{{/*{{- end }}*/}}
