apiVersion: v1
kind: Service
metadata:
  name: {{ include "vparking-settings.fullname" . }}
  labels:
    {{- include "vparking-settings.labels" . | nindent 4 }}
    app: {{ include "vparking-settings.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
   
  selector:
    {{- include "vparking-settings.selectorLabels" . | nindent 4 }}
    app: foo
