apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "vparking-settings.fullname" . }}-metrics
  labels:
     {{- include "vparking-settings.labels" . | nindent 4 }}
  namespace: {{.Release.Namespace}}
spec: 
  endpoints:
    {{- range $host := .Values.ingress.hosts }}
      {{- range $host.paths }}
    - port: http
      scheme: http
      path: /metrics
      interval: 60s
      {{- end}}
    {{- end}}
  selector:
      matchLabels:
        app: {{ include "vparking-settings.fullname" . }}
  namespaceSelector:
    matchNames:
      - {{.Release.Namespace}}
            
  