DO $$
BEGIN

    IF NOT EXISTS (
        SELECT 1 FROM pg_roles WHERE rolname = '${POSTGRES_CREATE_USER}'
    ) THEN
        CREATE ROLE "${POSTGRES_CREATE_USER}" LOGIN PASSWORD '${POSTGRES_CREATE_USER_PASSWORD}';
    END IF;
  
END $$;