name: argo-cd
home: https://github.com/argoproj/argo-helm
sources:
    - https://github.com/argoproj/argo-cd
    - https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd
version: 7.3.11-2
description: A Helm chart for Argo CD, a declarative, GitOps continuous delivery tool for Kubernetes.
keywords:
    - argoproj
    - argocd
    - gitops
maintainers:
    - name: argoproj
      email: ""
      url: https://argoproj.github.io/
icon: https://argo-cd.readthedocs.io/en/stable/assets/logo.png
apiversion: v2
condition: ""
tags: ""
appversion: v2.11.7
deprecated: false
annotations:
    artifacthub.io/changes: |
        - kind: changed
          description: Bump argo-cd to v2.11.7
    artifacthub.io/signKey: |
        fingerprint: 2B8F22F57260EFA67BE1C5824B11F800CD9D2252
        url: https://argoproj.github.io/argo-helm/pgp_keys.asc
kubeversion: '>=1.23.0-0'
dependencies:
    - name: redis-ha
      version: 4.26.1
      repository: https://dandydeveloper.github.io/charts/
      condition: redis-ha.enabled
      tags: []
      enabled: false
      importvalues: []
      alias: ""
type: ""
