apiVersion: v1
kind: Secret
metadata:
  name: settings-secret
data:
  database-server-name: "a2V5Y2xvYWstZGItcG9zdGdyZXNxbC5rZXljbG9hay5zdmMuY2x1c3Rlci5sb2NhbA=="
  database-user-name: "a2V5Y2xvYWs="
  database-user-password: "OVp1ek4wS1pIbA=="