apiVersion: v1
kind: Service
metadata:
  name: {{ include "vparking-service.fullname" . }}
  {{- with .Values.service.annotations}}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end}}
  labels:
    {{- include "vparking-service.labels" . | nindent 4 }}
    release: {{.Values.prometheus.release}}
    app: {{ include "vparking-service.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vparking-orders.selectorLabels" . | nindent 4 }}
    
