externalDatabase.password: "qwerty"
postgresql.auth.password: "qwerty"
ingress: 
  enabled: true
  ingressClassName: nginx
  hostname: keycloak.keycloak.svc.cluster.local
  pathType: ImplementationSpecific
proxy: edge
auth:
  adminUser: user
  password: qwerty
