apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
       k8s-app: oauth2-proxy
       app.kubernetes.io/app-version: 26.1.4                                                                                                                                                                                                       
       app.kubernetes.io/component: keycloak                                                                                                                                                                                                       
       app.kubernetes.io/instance: nginx                                                                                                                                                                                                           
       app.kubernetes.io/managed-by: Helm                                                                                                                                                                                                          
       app.kubernetes.io/name: keycloak                                                                                                                                                                                                            
       app.kubernetes.io/version: 26.1.4                                                                                                                                                                                                           
                                                                                                                                                                                                 
  name: oauth2-proxy
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
      - args:
        - --provider=keycloak-oidc
        - --redirect-url=https://arch.homework/oauth2/callback
        - --oidc-issuer-url=http://arch.homework/realms/vparking      
        - --email-domain=*
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --ssl-insecure-skip-verify=true
       
        - --silence-ping-logging=true
        - --reverse-proxy=true
        - --cookie-domain=arch.homework
        - --set-xauthrequest=true
        - --set-authorization-header=true
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          value: vparking
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: ap0C3RjBesn19VNzKMRs8FvoV6g0F3Px
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: ctqULBPoIvY1YuxAuUJGDg==
        image: quay.io/oauth2-proxy/oauth2-proxy@sha256:e01ded8323cc577440be301d8673cdd515367b8d9afe9eb23f61016a8c3e5f4e
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP

