apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
       k8s-app: oauth2-proxy
       app.kubernetes.io/app-version: 26.1.4                                                                                                                                                                                                       
       app.kubernetes.io/component: keycloak                                                                                                                                                                                                       
       app.kubernetes.io/instance: nginx                                                                                                                                                                                                           
       app.kubernetes.io/managed-by: Helm                                                                                                                                                                                                          
       app.kubernetes.io/name: keycloak                                                                                                                                                                                                            
       app.kubernetes.io/version: 26.1.4                                                                                                                                                                                                           
                                                                                                                                                                                                 
  name: oauth2-proxy
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
      - args:
        - --provider=keycloak-oidc
        - --redirect-url=https://nginx-keycloak.kube-system.svc.cluster.local/oauth2/callback
        - --oidc-issuer-url=http://nginx-keycloak.kube-system.svc.cluster.local/realms/vparking      
        - --email-domain=*
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --ssl-insecure-skip-verify=true
       
        - --silence-ping-logging=true
        - --reverse-proxy=true
        - --cookie-domain=arch.homework
        - --set-xauthrequest=true
        - --set-authorization-header=true
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          value: vparking
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: 9pDuhyYBFJ2kpaUK3fRTrwdUXqRWgJnuJ
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: ctqULBPoIvY1YuxAuUJGDg==
        image: cr.yandex/crpo2q44fm7kalr36b4h/oauth2-proxy@sha256:3b5a141880229d1abd38178f2b221bc813a740067bf830030a90ae6d37f51a1f
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP

