{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "vparking-settings.fullname" . }}
  labels:
    {{- include "vparking-settings.labels" . | nindent 4 }}
 
  annotations:
  {{- with .Values.ingress.annotations}}
      {{-  toYaml .  | nindent 4 }}
  {{- end }}
  {{- if .Values.ingress.authenticate}}
    nginx.ingress.kubernetes.io/auth-url: "http://oauth2-proxy.{{.Release.Namespace}}.svc.cluster.local/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "http:/$host/oauth2/start"
    nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, authorization"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
  {{- end}}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .pathPrefix }}{{.pathRegexSuffix}}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ include "vparking-settings.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
