apiVersion: v1
kind: Service
metadata:
  name: {{ include "vparking-settings.fullname" . }}
  {{- with .Values.service.annotations}}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end}}
  labels:
    {{- include "vparking-settings.labels" . | nindent 4 }}
    release: {{.Values.prometheus.release}}
    app: {{ include "vparking-settings.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
{{/*    {{- with .Values.service.ports}}*/}}
{{/*    - port: {{- .port }}*/}}
{{/*      targetPort: {{- .targetPort }}*/}}
{{/*      protocol: TCP*/}}
{{/*      name: {{- .name}}*/}}
{{/*    {{- end}}*/}}
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    - port: 22
      targetPort: 22
      protocol: TCP
      name: ssl
  selector:
    {{- include "vparking-settings.selectorLabels" . | nindent 4 }}
    
