name: redis-ha
home: http://redis.io/
sources:
    - https://github.com/DandyDeveloper/charts/blob/master/charts/redis-ha
    - https://github.com/oliver006/redis_exporter
    - https://redis.io/download
version: 4.26.1
description: This Helm chart provides a highly available Redis implementation with a master/slave configuration and uses Sentinel sidecars for failover management
keywords:
    - redis
    - keyvalue
    - database
maintainers:
    - name: ssalaues
      email: salimsalaues@gmail.com
      url: ""
    - name: dandydeveloper
      email: aaron.layfield@gmail.com
      url: ""
icon: https://upload.wikimedia.org/wikipedia/en/thumb/6/6b/Redis_Logo.svg/1200px-Redis_Logo.svg.png
apiversion: v2
condition: ""
tags: ""
appversion: 7.2.4
deprecated: false
annotations: {}
kubeversion: ""
dependencies: []
type: ""
