apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: oauth--proxy

build:
  artifacts:
    - image: vparking-users
      context: .
      docker:
        dockerfile: vparking-gateway/Dockerfile
        
    - image: vparking-orders
      context: .
      docker:
        dockerfile: vparking-order/Dockerfile-order
      
    - image: vparking-orders-update
      context: .
      docker:
        dockerfile: vparking-order/Dockerfile-update-order
         
    - image: vparking-billing
      context: .
      docker:
        dockerfile: vparking-billing/Dockerfile
        
    - image: vparking-billing-update
      context: .
      docker:
        dockerfile:  vparking-billing/Dockerfile-update
        
    - image: vparking-notification
      context: .
      docker:
        dockerfile: vparking-notification/Dockerfile
        
    - image: vparking-notification-update
      context: .
      docker:
        dockerfile: vparking-notification/Dockerfile-update
    
deploy:
  helm:
    releases:
#      - name: prometheus
#        chartPath: kube-prometheus-stack
#        namespace: monitoring
#        createNamespace: true
#        skipBuildDependencies: true
#        valuesFiles:
#            - kube-prometheus-stack/values.yaml
#      - name: ingress
#        chartPath: ingress-nginx
#        namespace: nginx-ingress
#        createNamespace: true
#        skipBuildDependencies: true
#        valuesFiles:
#            - ingress-nginx/values.yaml
#            - ingress-nginx/nginx-metrix-new.yaml
      - name: vparking-settings
        chartPath: vparking-gateway/vparking-settings
        namespace: keycloak
        createNamespace: true
        skipBuildDependencies: true
        valuesFiles:
          - vparking-gateway/vparking-settings/values.yaml
        version: 0.1.0
      - name: vparking-orders
        chartPath: vparking-order/helm
        namespace: orders
        createNamespace: true
        skipBuildDependencies: true
        valuesFiles:
          - vparking-order/helm/values.yaml
        version: 0.1.0
      - name: vparking-billing
        chartPath: vparking-billing/helm
        namespace: billing
        createNamespace: true
        skipBuildDependencies: true
        valuesFiles:
           - vparking-billing/helm/values.yaml
        version: 0.1.0
      - name: vparking-notification
        chartPath: vparking-notification/helm
        namespace: notification
        createNamespace: true
        skipBuildDependencies: true
        valuesFiles:
          - vparking-notification/helm/values.yaml
        version: 0.1.0