apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.serviceName}}-secret
  {{- with .Values.podAnnotations}}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end}}
data:
  password: {{.Values.dbAuth.password | b64enc}}
  postgres-password: "{{.Values.dbAuth.postgresPassword | b64enc}}"