apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-settings
data:
  hello-world: "hello"
  db-username: "{{.Values.postgresql.auth.username}}"
  db-server: "{{.Values.postgresql.fullnameOverride}}"
  {{- with (index .Values.ingress.hosts 0)}}
    {{- with (index .paths 0)}}
  swagger-prefix: "{{.pathPrefix}}"
    {{- end}}
  {{- end}}
  