apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vparking-settings.fullname" . }}
  {{- with .Values.podAnnotations}}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end}}
  labels:
    {{- include "vparking-settings.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vparking-settings.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vparking-settings.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vparking-settings.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{include "image.fullName" .}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: ssl
              containerPort: 22
              protocol: TCP
          env:
            - name: "URL"
              value: {{.Values.keycloak.url}}
            - name: "REALM"
              value: {{.Values.keycloak.realm}}
            - name: "CLIENT_ID"
              value: {{.Values.keycloak.clientId}}
            - name: "USER_NAME"
              value: {{.Values.keycloak.auth.user}}
            - name: "USER_PASSWORD"
              value: {{.Values.keycloak.auth.password}}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
